### ISSUE TITLE
Fail to parse preload data

### ISSUE THREAD

**Issue by vbalazs913** [rebornix/uptime-kuma-monitor#2]
I'm getting a "Fail to parse preload data" error when entering my status page URL. Important to note that the status page is hosted internally, so it's not reachable from the internet, but still, my computer is connected to the internal network.

**Comment by rebornix** [comment]
@vbalazs913 sorry for the late response, do you mind sharing the version of Uptime Kuma you are using?

**Comment by vbalazs913** [comment]
@rebornix I'm using version 1.1

**Comment by rebornix** [comment]
@vbalazs913 just to double confirm, are you using Uptime Kuma 1.1?

**Comment by vbalazs913** [comment]
@rebornix yes, i'm on 1.1

**Comment by rebornix** [comment]
@vbalazs913 thanks, I only tested 1.19 and 1.21 (latest) but didn't check the old versions, maybe the content format is different on those old ones, will give them a try.

**Comment by vbalazs913** [comment]
@rebornix oh so there's a newer version? i'm using the app store version, how do i get the newer one? i'm on a m1 macbook pro

**Comment by rebornix** [comment]
@vbalazs913 ah sorry I'm asking what version of "Uptime Kuma" server you are using, not the macOS app.

**Comment by vbalazs913** [comment]
@rebornix that, i'm not quite sure, will check as soon as i can, thank you for the clarification.

**Comment by rebornix** [comment]
@vbalazs913 you can figure that out by visiting your Uptime Kuma webpage, top right user icon -> settings -> about, to find out what version you are using, thanks!

**Comment by vbalazs913** [comment]
@rebornix we're using 1.21.2, according to github, it's the latest

**Comment by casudo** [comment]
I do get the same error, even tho my status page is available for the public.

**Comment by vbalazs913** [comment]
@rebornix the https://status.kuma.pet site works and show perfectly fine, but our page that we use internally is not working, even though we're on the same network as the monitor.

**Comment by uhlhosting** [comment]
I got same issues, using latest Kuma stable. the above link mentioned by vbalazs works, yet mine does not.

https://status.kuma.pet works
https://uptime.uhl.cloud not working

**Comment by uhlhosting** [comment]
@rebornix any ideas why these do not work?

**Comment by vbalazs913** [comment]
is there a chance that the number of items cause the error? my page has 119 entries, could that be the problem?

**Comment by uhlhosting** [comment]
Anyone???

**Comment by uhlhosting** [comment]
@rebornix
